#Define the base image we'll be building everything else off of...
FROM microsoft/python

#Give it a label
LABEL Description="DevPythonApp" Vendor="bundyfx" Version="1.5.9"

#
#These files and folders will be imported into the docker image and be available for us to use.
#

ADD git/python/files/test.py /inetpub/wwwroot/index.html

ENTRYPOINT CMD
