#Define the base image we'll be building everything else off of...
FROM microsoft/django

#Give it a label
LABEL Description="DevDjangoApp" Vendor="bundyfx" Version="1.6.0"

#
#These files and folders will be imported into the docker image and be available for us to use.
#


ADD /manage.py  /python/manage.py
ADD /setup.py  /python/setup.py
ADD /helloworld /python/helloworld

ENTRYPOINT CMD

