#Define the base image we'll be building everything else off of...
FROM microsoft/sample-golang:windowsservercore

#Give it a label
LABEL Description="DevGOApp" Vendor="bundyfx" Version="1.7.4"

#
#These files and folders will be imported into the docker image and be available for us to use.
#

ADD /webserver.go /go/src/webserver.go

CMD go run C:\go\src\webserver.go

