
[ClassVersion("1.0.0.0"), FriendlyName("ContainerDeployment")]
class ContainerDeployment : OMI_BaseResource
{
    [Key] String ContainerName;
    [Key] String PortMapping;
    [Key] String ProjectRootPath;
    [Key] String GitProjectURL;
    [Key, ValueMap{"sample-golang","iis"}, Values{"sample-golang","iis"}] String ProjectType;
    [Key] String ContainerImage;
    [Key, ValueMap{"Absent","Present"}, Values{"Absent","Present"}] String Ensure;
};

