#Define the base image we'll be building everything else off of...
FROM microsoft/iis:windowsservercore

#Give it a label
LABEL Description="DevIISApp" Vendor="bundyfx" Version="1.7.7"

#
#These files and folders will be imported into the docker image and be available for us to use.
#

ADD /index.html /inetpub/wwwroot/index.html

RUN CMD
