#Define the base image we'll be building everything else off of...
FROM microsoft/golang

#Give it a label
LABEL Description="DevGOApp" Vendor="bundyfx" Version="1.6.4"

#
#These files and folders will be imported into the docker image and be available for us to use.
#

ADD /webserver.go /go/src/webserver.go

CMD ["go run", "/go/src/webserver.go"]

